=== venkatesh185/web_lab/XML/library.dtd
<!ELEMENT college (Student)*>
<!ATTLIST Student to CDATA "Student">
<!ELEMENT Student (name,rno,branch)>
<!ELEMENT name (#PCDATA)*>
<!ELEMENT rno (#PCDATA)*>
<!ELEMENT branch (#PCDATA)*>
<!ELEMENT college (Teaching)*>
<!ATTLIST Teaching to CDATA "Teaching">
<!ELEMENT Teaching (name,Dept,empid)>
<!ELEMENT name (#PCDATA)*>
<!ELEMENT Dept (#PCDATA)*>
<!ELEMENT empid (#PCDATA)*>
<!ELEMENT college (NonTeaching)*>
<!ATTLIST NonTeaching to CDATA "NonTeaching">
<!ELEMENT NonTeaching (name,id,block)>
<!ELEMENT name (#PCDATA)*>
<!ELEMENT id (#PCDATA)*>
<!ELEMENT block (#PCDATA)*>

=== venkatesh185/web_lab/XML/week5a.xml
<!DOCTYPE library SYSTEM "library.dtd">
<?xml-stylesheet type="text/xsl" href="week5a.xsl"?>
<?xml version="1.0" standalone="no"?>
<college>
<Student to="student">
<name>ABC</name>
<rno>19-88</rno>
<branch>CSE</branch>
</Student>
<Teaching to="teaching">
<name>ECD</name>
<Dept>CSE</Dept>
<empid>f001</empid>
</Teaching>
<NonTeaching to="non-teaching">
<name>MNO</name>
<id>ct01</id>
<block>B4-301</block> 
</NonTeaching>
</college>
