=== venkatesh185/web_lab/XML/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.javatpoint.com"
xmlns="http://www.javatpoint.com"
elementFormDefault="qualified">
<xs:element name="college">
<xs:complexType>
<xs:sequence>
<xs:element name="student" type="studenttype"></xs:element>
<xs:element name="faculty" type="facultytype"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:complexType name="studenttype">
<xs:sequence>
<xs:element name="name" type="xs:string"></xs:element>
<xs:element name="rollno" type="xs:string"></xs:element>
<xs:element name="branch" type="xs:string"></xs:element>
<xs:element name="section" type="xs:integer"></xs:element>
<xs:element name="year" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>
<xs:complexType name="facultytype">
<xs:sequence>
<xs:element name="name" type="xs:string"></xs:element>
<xs:element name="id" type="myId"></xs:element>
<xs:element name="dept" type="xs:string"></xs:element>
<xs:element name="subject" type="xs:string"></xs:element>
</xs:sequence>
</xs:complexType>

<xs:simpleType name="myId">
<xs:restriction base="xs:integer">
<xs:minInclusive value="1"></xs:minInclusive>
<xs:maxInclusive value="1000000"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
</xs:schema>

=== venkatesh185/web_lab/XML/xm.xml
<?xml version="1.0" encoding="UTF-8"?>
<college
xmlns="http://www.javatpoint.com" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.javatpoint.com schema.xsd"> 
  <student>
    <name>Kaushik</name>
    <rollno>19131A05L0</rollno>
    <branch>CSE</branch>
    <section>4</section>
    <year>3rd</year>
  </student>
  <faculty>
    <name>Akhila</name>
    <id>567532</id>
    <dept>CSE</dept>
    <subject>WEB TECHECHNOLOGIES LAB</subject>
  </faculty>
</college>
